# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array1.reshape(2,5) # convert a 1D into 2D array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
a1 = np.arange(0,10).reshape(2,5)
b1 = np.ones((2,5),dtype=int).reshape(2,5)
np.vstack((a1,b1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
a1 = np.arange(0,10).reshape(2,5)
b2 = np.ones((2,5),dtype=int).reshape(2,5)
np.hstack((a1,b1)) # stack two arrays horizontally

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
a = np.array([0,1,2,3,4,5,6,7,8,9,]).reshape(5,2)
np.ravel(a) # convert an arrays into a flat 1d array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [18]:
a1 = np.arange(0,15).reshape(5,3)
a1 = np.arange(0,15).reshape(1,15) #convert higher dimention into one dimension
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [20]:
a1 = np.arange(0,15)
a1.ravel() # conversion of one dimension to higher dimension


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:7

### Create 5x5 an array and find the square of an array?

In [31]:
a1 = np.arange(4,29).reshape(5,5)
a1
np.square(a1) #cal the square of an array


array([[ 16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169],
       [196, 225, 256, 289, 324],
       [361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [37]:
a1 = np.arange(4,34).reshape(5,6)
a1.mean() # cal the mean of array 

18.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [38]:
a1.std() # cal the standard deviation of the previous array in Q8

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [39]:
np.median(a1) # cal the median of the previous array in Q8

18.5

## Question:11

### Find the transpose of the previous array in Q8?

In [40]:
a1.transpose() # transpose of the previous array in Q8

array([[ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30],
       [ 7, 13, 19, 25, 31],
       [ 8, 14, 20, 26, 32],
       [ 9, 15, 21, 27, 33]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [41]:
a2 = np.random.randn(4,4) # created 4X4 array
a2.diagonal() # this statement cal the diagonal elements of array

array([ 1.31404416,  0.64669399, -0.76213848, -1.68891152])

## Question:13

### Find the determinant of the previous array in Q12?

In [42]:
np.linalg.det(a2) # find the determinant of the a2 variable

2.934913752754176

## Question:14

### Find the 5th and 95th percentile of an array?

In [53]:
a3 = np.arange(100).reshape(25,4)
a3
np.percentile (a3, 5, axis=None, out=None) # find the 5th percentile of an array

4.95

In [52]:
a3 = np.arange(100).reshape(25,4)
a3
np.percentile (a3, 95, axis=None, out=None) # find the 95th percentile of an array

94.05

## Question:15

### How to find if a given array has any null values?

In [61]:
a4 = np.array([50,np.NaN,80,45,85,np.NaN,97,23,0,12])
a4
np.isnan(a4) # find the null values s boolean True

array([False,  True, False, False, False,  True, False, False, False,
       False])

In [63]:
a4

array([50., nan, 80., 45., 85., nan, 97., 23.,  0., 12.])